version: 2
jobs:
  build:
    working_directory: ~/circleci2
    docker:
      - image: circleci/php:7.1.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Clone Laradock
          command: git clone https://github.com/laradock/laradock.git
