version: 2
jobs:
  build:
    working_directory: ~/circleci2
    docker:
      - image: docker/compose:1.14.0
    steps:
      - checkout
      - run:
          name: Clone Laradock
          command: git clone https://github.com/laradock/laradock.git
